include: "rules/common.smk"

configfile: "configs/config.yaml"

##### Target rules #####
rule all:
    input:
        fastp_output,
        "results/fastps_multiqc.html",
        expand(
            "results/mapped/{u.sample}.bqsr.bam",
            u=input_data.itertuples(),
        )

##### Modules #####
include: "rules/fastp.smk"
include: "rules/mapping.smk"
