# conda environment configuration for snakemake
name: preDNAnalyzer
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - snakemake-minimal>=7.0
    - python>=3.8
    - pandas
    - numpy
    - pip
